services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: db_stock
    ports:
      - "5433:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"

networks:
  default:
    name: ms