spring:
  application:
    name: ms-order
  datasource:
    url: jdbc:postgresql://localhost:5434/db_order
    username: user
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8085
