spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_client
    username: user
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

